### PR TITLE
chore: resolves issue 28 and 25

### LINKED ISSUE #25: Doesn't compile with libsass
Trying to compile with sassc (node-sass should be the same) yields:

```
Error: Import directives may not be used within control directives or mixins.
        on line 28 of sierra/src/_sierra.scss
>>   @import 'scss/flexboxgrid';
   --^
```

`@import` inside `@if` statements are apparently not really supported by sass, they just happen to work with the ruby compiler.

### LINKED ISSUE #28: Rename "entry" to something better namespaced
If someone wants to use Bower to install Sierra, and then use `bower_components\sierra\src` as a location to look for items being imported they'd have to use the generic `@import "entry"` which is not very descriptive and would lend itself to importing in the wrong file from a different directory.

`entry.scss` should be renamed to `sierra-entry.scss` or something similarly namespaced.

See how the following mixin libraries follow this same pattern:

Code                                     | Source
:--                                      | :--
`@import "buttons";`                     | [github.com/alexwolfe/Buttons](https://github.com/alexwolfe/Buttons)
`@import "saffron";`                     | [github.com/corporadobob/saffron](https://github.com/corporadobob/saffron)
`@import "sassmatic";`                   | [github.com/DarbyBrown/sassmatic](https://github.com/DarbyBrown/sassmatic)
`@import "scut";`                        | [github.com/davidtheclark/scut](https://github.com/davidtheclark/scut)
`@import "su";`                          | [github.com/ericam/susy](https://github.com/ericam/susy)
`@import "susy";`                        | [github.com/ericam/susy](https://github.com/ericam/susy)
`@import "susyone";`                     | [github.com/ericam/susy](https://github.com/ericam/susy)
`@import "andy";`                        | [github.com/gillesbertaux/andy](https://github.com/gillesbertaux/andy)
`@import "typesettings";`                | [github.com/ianrose/typesettings](https://github.com/ianrose/typesettings)
`@import "animate";`                     | [github.com/Igosuki/compass-mixins](https://github.com/Igosuki/compass-mixins)
`@import "compass";`                     | [github.com/Igosuki/compass-mixins](https://github.com/Igosuki/compass-mixins)
`@import "lemonade";`                    | [github.com/Igosuki/compass-mixins](https://github.com/Igosuki/compass-mixins)
`@import "sassy-buttons";`               | [github.com/jhardy/Sassy-Buttons](https://github.com/jhardy/Sassy-Buttons)
`@import "bluebird";`                    | [github.com/kalebheitzman/bluebird](https://github.com/kalebheitzman/bluebird)
`@import "sass-easing";`                 | [github.com/kingscooty/sass-easing](https://github.com/kingscooty/sass-easing)
`@import "breakpoint";`                  | [github.com/lesjames/breakpoint](https://github.com/lesjames/breakpoint)
`@import "css3-mixins";`                 | [github.com/matthieua/sass-css3-mixins](https://github.com/matthieua/sass-css3-mixins)
`@import "cssowl";`                      | [github.com/owl-stars/cssowl](https://github.com/owl-stars/cssowl)
`@import "spice";`                       | [github.com/spice-sass/spice](https://github.com/spice-sass/spice)
`@import "bourbon-deprecated-upcoming";` | [github.com/thoughtbot/bourbon](https://github.com/thoughtbot/bourbon)
`@import "bourbon";`                     | [github.com/thoughtbot/bourbon](https://github.com/thoughtbot/bourbon)
`@import "neat";`                        | [github.com/thoughtbot/neat](https://github.com/thoughtbot/neat)

Since this may be a breaking change for those who explicitly targeted `bower_components\sierra\src\entry.scss` you should include a major version bump from `v1.1.4` to `v2.0.0`.

### PR DESCRIPTION
**Pull request by maraisr**
Fixes #25 
Fixes #28

### CODE REVIEW

**Comment by JoanClaret** [comment]
Great!
Please, next time, use single pull request for each issue.
Thank you!

**Comment by JoanClaret** [comment]
Thanks for using postcss. love it!
Please, use tabs instead of spaces for indent js files.
Great work anyway!

**Comment by jezmck** [comment]
No, use spaces.

**Comment by elboletaire** [comment]
+1 for spaces.

BTW, I recommend you using [editorconfig](http://editorconfig.org/) to avoid this kind of issues.

**Comment by JoanClaret** [comment]
i said tabs because all file was indented with tabs. 
@maraisr used spaces, so we've got the file with tabs and spaces, which i think is even worst than using only tabs.

anyway, by popular demand, let's use spaces!

**Comment by JoanClaret** [comment]
b512142369244e643c0aea08858d9bcb21ead94c

**Comment by elboletaire** [comment]
> used spaces, so we've got the file with tabs and spaces, which i think is even worst than using only tabs.

That's why I said to use editorconfig. Using editorconfig you won't have this kind of problems in the future ;)

**Comment by jezmck** [comment]
editorconfig requires other people to be using editorconfig.

spaces are spaces

**Comment by JoanClaret** [comment]
spaces are spaces, indeed.

btw, editorconfig file was already included in the library (with spaces!) 
;)

**Pull request merged**
